# NOTE: This mkdocs.yml contains the minimum config required to run
# Airlock's docs locally and to access them within Airlock itself.
#
# In production, the airlock docs are also pulled into and built with
# the main docs at https://github.com/opensafely/documentation
#
# The contents of this mkdocs.yml are ignored in the production build.
#
site_name: Airlock Documentation
repo_url: https://github.com/opensafely-core/airlock
docs_dir: docs
site_dir: mkdocs_build

nav:
  - About: index.md
  - How-to guides:
    - how-tos/index.md
    - How to access and log in Airlock: how-tos/access-airlock.md
    - For researchers:
      - View output files in a workspace: how-tos/view-workspace-files.md
      - Create and submit a release request: how-tos/create-and-submit-a-release-request.md
      - Respond to a returned request: how-tos/respond-to-returned-request.md
      - Update a file on a request: how-tos/update-file-on-request.md
      - Withdraw a file from a request: how-tos/withdraw-file.md
      - Withdraw a request: how-tos/withdraw-request.md
    - For output checkers:
      - Review a request: how-tos/review-a-request.md
      - Download a file: how-tos/download-file.md
      - Reject a request: how-tos/reject-request.md
      - Release files: how-tos/release-files.md
  - Explanation: 
    - explanation/index.md
    - Why Airlock?: explanation/why-airlock.md
    - Workflow and permissions: explanation/workflow-and-permissions.md
    - Notifications: explanation/notifications.md
  - Reference:
    - reference/index.md
    - reference/terms-and-definitions.md
    - Alternative ways to view files: reference/view-files-alt.md
    - Viewing underlying source code: reference/view-source-code.md
    - Request state diagram: reference/request-states.md

watch:
  - docs

# WARNING!
# Most of the rest of this config (see comments for exceptions) is duplicated from the mkdocs.yml
# in the parent repo (https://github.com/opensafely/documentation) in order to build in-airlock docs with
# similar styling. If any changes/additions are needed, ensure they are
# made in the parent repo also.

copyright: © University of Oxford for the Bennett Institute for Applied Data Science. This work may be copied freely for non-commercial research and study. If you wish to do any of the other acts restricted by the copyright you should apply in writing to bennett@phc.ox.ac.uk.

theme:
  name: material
  font: false
  logo: img/icon.svg
  favicon: img/favicon.svg
  palette:
    scheme: opensafely
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.indexes
  # Note: specific to in-airlock docs (main docs have different template overrides);
  # adds the link back to airlock
  custom_dir: docs/overrides

extra_css:
  - stylesheets/extra.css
  - stylesheets/airlock.css  # Note: extra styling specific to in-airlock docs

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "🔗"
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - admonition
  - footnotes
  - abbr
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      check_paths: true
      base_path: # base paths will be checked in order for matching snippets
        - docs
