# Generated by Django 5.0.1 on 2024-02-13 12:36

import django.utils.timezone
from django.db import migrations, models

import local_db.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestMetadata",
            fields=[
                (
                    "id",
                    models.TextField(
                        default=local_db.models.local_request_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("workspace", models.TextField()),
                ("author", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
