# Generated by Django 5.0.2 on 2024-02-16 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0002_requestmetadata_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileGroupMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="default")),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filegroups",
                        to="local_db.requestmetadata",
                    ),
                ),
            ],
            options={
                "unique_together": {("request", "name")},
            },
        ),
        migrations.CreateModel(
            name="RequestFileMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relpath", models.TextField()),
                (
                    "filegroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_files",
                        to="local_db.filegroupmetadata",
                    ),
                ),
            ],
            options={
                "unique_together": {("relpath", "filegroup")},
            },
        ),
    ]
