# Generated by Django 5.0.2 on 2024-02-16 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0003_filegroupmetadata_requestfilemetadata"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="requestfilemetadata",
            unique_together={("relpath", "filegroup")},
        ),
    ]
