# Generated by Django 5.0.3 on 2024-03-25 13:18

import django.utils.timezone
from django.db import migrations, models

import local_db.models


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0006_filereview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filereview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", local_db.models.EnumField()),
                ("user", models.TextField()),
                ("workspace", models.TextField(null=True)),
                ("request", models.TextField(null=True)),
                ("path", models.TextField(null=True)),
                ("extra", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="local_db_au_user_90f771_idx"),
                    models.Index(
                        fields=["workspace"], name="local_db_au_workspa_e902d0_idx"
                    ),
                    models.Index(
                        fields=["request"], name="local_db_au_request_5ac48b_idx"
                    ),
                ],
            },
        ),
    ]
