# Generated by Django 5.0.3 on 2024-03-27 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0007_alter_filereview_updated_at_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filereview",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="reviews",
                to="local_db.requestfilemetadata",
            ),
        ),
    ]
