# Generated by Django 5.0.3 on 2024-04-04 15:05

from django.db import migrations


def add_request_to_requestfile(apps, schema_editor):
    # Use the filegroup to add the request to each file
    # We'll make the request non-nullable in the next migration
    RequestFileMetadata = apps.get_model("local_db", "RequestFileMetadata")
    for request_file in RequestFileMetadata.objects.all():  # pragma: no cover
        request_file.request_id = request_file.filegroup.request.id
        request_file.save()


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0010_requestfilemetadata_request"),
    ]

    operations = [
        migrations.RunPython(
            add_request_to_requestfile, reverse_code=migrations.RunPython.noop
        ),
    ]
