# Generated by Django 5.0.3 on 2024-04-04 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0011_add_request_to_requestfilemetadata"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="requestfilemetadata",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="requestfilemetadata",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_files",
                to="local_db.requestmetadata",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="requestfilemetadata",
            unique_together={("relpath", "request")},
        ),
    ]
