# Generated by Django 5.0.3 on 2024-04-15 09:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0012_alter_requestfilemetadata_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filegroupmetadata",
            name="context",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="filegroupmetadata",
            name="controls",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="filegroupmetadata",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="filegroupmetadata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="FileGroupComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("author", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "filegroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="local_db.filegroupmetadata",
                    ),
                ),
            ],
        ),
    ]
