# Generated by Django 5.0.4 on 2024-05-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "local_db",
            "0013_filegroupmetadata_context_filegroupmetadata_controls_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="requestfilemetadata",
            name="col_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="requestfilemetadata",
            name="commit",
            field=models.TextField(default="abcd"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requestfilemetadata",
            name="job_id",
            field=models.TextField(default="1234"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requestfilemetadata",
            name="row_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="requestfilemetadata",
            name="size",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requestfilemetadata",
            name="timestamp",
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
