# Generated by Django 5.0.4 on 2024-05-07 12:46

from django.db import migrations

from airlock.business_logic import BusinessLogicLayer, Workspace


def update_manifest_data(apps, schema_editor):
    RequestFileMetadata = apps.get_model("local_db", "RequestFileMetadata")
    for request_file in RequestFileMetadata.objects.all():  # pragma: no cover
        workspace = Workspace(name=request_file.request.workspace)
        try:
            manifest_data = workspace.get_manifest_for_file(
                relpath=request_file.relpath
            )
        except (BusinessLogicLayer.FileNotFound, KeyError):
            print(
                f"Could not update manifest.json data for {workspace.name}/{request_file.relpath}"
            )
            continue
        request_file.timestamp = manifest_data["timestamp"]
        request_file.size = manifest_data["timestamp"]
        request_file.commit = manifest_data["timestamp"]
        request_file.job_id = manifest_data["timestamp"]
        request_file.row_count = manifest_data.get("row_count")
        request_file.col_count = manifest_data.get("col_count")
        request_file.save()


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0014_requestfilemetadata_col_count_and_more"),
    ]

    operations = [
        migrations.RunPython(
            update_manifest_data, reverse_code=migrations.RunPython.noop
        ),
    ]
