# Generated by Django 5.0.4 on 2024-05-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0014_requestfilemetadata_col_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestfilemetadata",
            name="repo",
            field=models.URLField(default="http://example.com"),
            preserve_default=False,
        ),
    ]
