# Generated by Django 5.0.6 on 2024-05-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0015_requestfilemetadata_repo"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestfilemetadata",
            name="release_date",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="requestfilemetadata",
            name="release_output_checker",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
