# Generated by Django 5.0.6 on 2024-06-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0016_requestfilemetadata_released_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestmetadata",
            name="completed_reviews",
            field=models.JSONField(default=dict),
        ),
    ]
