# Generated by Django 5.0.6 on 2024-07-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0018_filegroupcomment_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="filegroupcomment",
            name="review_turn",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requestmetadata",
            name="review_turn",
            field=models.IntegerField(default=0),
        ),
    ]
