# Generated by Django 5.0.7 on 2024-07-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0019_filegroupcomment_review_round_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestmetadata",
            name="turn_reviewers",
            field=models.TextField(null=True),
        ),
    ]
