# Generated by Django 5.0.7 on 2024-07-24 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0020_requestmetadata_turn_reviewers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requestmetadata",
            old_name="completed_reviews",
            new_name="submitted_reviews",
        ),
    ]
