# Generated by Django 5.0.7 on 2024-07-26 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0021_auto_20240719_1043"),
        ("local_db", "0021_rename_completed_reviews_requestmetadata_submitted_reviews"),
    ]

    operations = []
