# Generated by Django 5.0.7 on 2024-07-26 14:36

from django.db import migrations


# We've changed RequestFileVote.REJECTED to
# RequestFileVote.CHANGES_REQUESTED, which requires a change to the
# database.
#
# We'd like to have a RunPython migration like the following, but that fails
# because the status parameter is expected to be an instance of RequestFileVote
#
# def update_column_values(apps, schema_editor):
#     FileReview = apps.get_model("local_db", "FileReview")
#     FileReview.objects.filter(type="REJECTED").update(
#         type="CHANGES_REQUESTED"
#     )
#
# We could work around that by sequencing the migration across two deploys, but
# it's easier to write some SQL.

sql = "UPDATE local_db_filereview SET status = %s WHERE status = %s"
old = "REJECTED"
new = "CHANGES_REQUESTED"


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0022_merge_20240726_0910"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[(sql, [new, old])],
            reverse_sql=[(sql, [old, new])],
        ),
    ]
