# Generated by Django 5.1.5 on 2025-02-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0023_auto_20240726_1436"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestfilemetadata",
            name="upload_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="requestfilemetadata",
            name="uploaded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="requestfilemetadata",
            name="uploaded_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
