# Generated by Django 5.1.7 on 2025-03-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0025_requestfilemetadata_upload_attempted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="filereview",
            name="review_turn",
            field=models.IntegerField(null=True),
        ),
    ]
