# Generated by Django 5.2.10 on 2026-02-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0027_auditlog_hidden_alter_filereview_review_turn"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestmetadata",
            name="organisations",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="requestmetadata",
            name="project",
            field=models.TextField(default=""),
        ),
    ]
