# Generated by Django 5.2.12 on 2026-03-09 14:32

from django.db import migrations, models

from airlock.enums import AuditEventType


def backfill_last_submitted_at(apps, schema_editor):  # pragma: no cover
    RequestMetadata = apps.get_model("local_db", "RequestMetadata")
    AuditLog = apps.get_model("local_db", "AuditLog")

    for request in RequestMetadata.objects.all():
        last_submission_audit_event = (
            AuditLog.objects.filter(
                request=request.id, type=AuditEventType.REQUEST_SUBMIT
            )
            .order_by("created_at")
            .last()
        )

        if last_submission_audit_event:
            request.last_submitted_at = last_submission_audit_event.created_at
            request.save()


class Migration(migrations.Migration):
    dependencies = [
        ("local_db", "0028_requestmetadata_organisations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestmetadata",
            name="last_submitted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(
            code=backfill_last_submitted_at,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
