---
name: CI

on:
  # On `main` we are invoked by the deploy workflow rather than running automatically
  push:
    branches-ignore: [main]
  # Allow this workflow to be invoked by the deploy workflow and specify where to
  # persist the resulting Docker image
  workflow_call:
    inputs:
      build-artifact-name: {type: string, required: false}

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: "opensafely-core/setup-action@d9171097dd0d37bdb7bed58f701eb03ff317ed17" # v1
        with:
          install-just: true
          install-uv: true
          cache: uv
      - name: Set up development environment
        run: just devenv
      - name: Check formatting and linting rules
        run: just check
      - name: Check renovate config
        run: just check-renovate-config

  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: "opensafely-core/setup-action@d9171097dd0d37bdb7bed58f701eb03ff317ed17" # v1
        with:
          install-just: true
          install-uv: true
          cache: uv

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: ".node-version"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Set up development environment
        run: just devenv

      - name: Run tests
        run: |
          TAKE_SCREENSHOTS=True just test-all

      # not actually needed for tests, but we want to make sure the dev tooling
      # is still working
      - name: Validate load-example-data dev tooling works
        run: |
            just manage migrate
            just load-example-data
 

  docker-test-dev:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: "opensafely-core/setup-action@d9171097dd0d37bdb7bed58f701eb03ff317ed17" # v1
        with:
          install-just: true
          install-uv: true
          cache: uv

      - name: Build docs
        run: |
          just docs-build

      - name: Build docker image for both prod and dev
        run: |
            just docker/build dev

      - name: Run unit tests on docker dev image
        run: |
          # build docker and run test
          just docker/test


  docker-test-prod:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: "opensafely-core/setup-action@d9171097dd0d37bdb7bed58f701eb03ff317ed17" # v1
        with:
          install-just: true
          install-uv: true
          cache: uv

      - name: Build docs
        run: |
            just docs-build

      - name: Build docker image for both prod and dev
        run: |
            just docker/build prod

      - name: Run smoke test on prod
        run: |
          just docker/serve prod -d
          sleep 5
          just docker/smoke-test || { docker logs airlock-prod-1; exit 1; }

      - name: Save image as artifact
        uses: ./.github/actions/save-image-as-artifact
        with:
          image-name: airlock
          artifact-name: ${{ inputs.build-artifact-name }}

  required-checks:
    if: always()

    needs:
      - check
      - test
      - docker-test-dev
      - docker-test-prod

    runs-on: ubuntu-24.04

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # v1.3.0
        with:
          jobs: ${{ toJSON(needs) }}
