---
name: Local job-server setup CI

on:
  schedule: 
    # every day at 2:37am
    - cron: "37 2 * * *"

jobs:
  test-local-job-server:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5
      - uses: "opensafely-core/setup-action@v1"
        with:
          python-version: "3.11"
          install-just: true
 
      - name: "Test local job server setup"
        # this should download, configure and successfully launch a local job-server
        # we test it to make sure we catch breaking changes in job-server configuration we need to update.
        run: |
          just _dotenv  # we don't need a full devenv
          just job-server/configure username
          just job-server/create-workspace test-workspace
