---
name: Local job-server setup CI

on:
  schedule: 
    # every day at 2:37am
    - cron: "37 2 * * *"

permissions:
  contents: read

jobs:
  test-local-job-server:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: "opensafely-core/setup-action@d9171097dd0d37bdb7bed58f701eb03ff317ed17" # v1
        with:
          python-version: "3.12"
          install-just: true
 
      - name: "Test local job server setup"
        # this should download, configure and successfully launch a local job-server
        # we test it to make sure we catch breaking changes in job-server configuration we need to update.
        run: |
          just _dotenv  # we don't need a full devenv
          just job-server/configure username
          just job-server/create-workspace test-workspace
