---
name: Docs

on:
  push:
    branches-ignore:
      - main

jobs:
  check_for_docs_changes:
    permissions:
      contents: read
    
    runs-on: ubuntu-latest
    
    outputs:
      changed: ${{ steps.git_diff_docs.outputs.changed }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # Required to get main branch for comparison
          fetch-depth: 0
    
      - name: Check if docs have changed
        id: git_diff_docs
        run: echo "changed=`git diff origin/main -s --exit-code mkdocs.yml docs || echo 1`" >> "$GITHUB_OUTPUT"

  deploy:

    permissions:
      contents: read
      deployments: write

    runs-on: ubuntu-latest
    
    needs: check_for_docs_changes
    
    if: ${{ needs.check_for_docs_changes.outputs.changed }}
    
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Install Python and just
        uses: opensafely-core/setup-action@v1
        with:
          install-just: true
          python-version: "3.11"

      - name: Build site
        run: just docs-build

      - name: Add a version file
        run: echo ${{ github.sha }} > mkdocs_build/version.html

      - name: Publish
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca  # v1.5.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_DIRECT_UPLOAD_API_TOKEN }}
          directory: "mkdocs_build"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: "airlock-docs"
