---
name: trace-functional-tests

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 3 * * *"

permissions:
  contents: read

jobs:

  trace-functional-tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: "opensafely-core/setup-action@d9171097dd0d37bdb7bed58f701eb03ff317ed17" # v1
        with:
          install-just: true
          install-uv: true
          cache: uv

      - name: Install Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: ".node-version"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install node_modules
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Set up development environment
        run: just devenv

      - name: Run functional tests
        id: run_test
        run: |
          HYPOTHESIS_MAX_EXAMPLES=100 just test -k functional --tracing retain-on-failure
        
      - name: Upload trace artifact
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
            name: test-results-trace
            path: test-results/**/trace.zip

      - name: Notify slack of failures
        if: failure()
        uses: slackapi/slack-github-action@0d95c9a7becc1e6e297d76df9bc735c44f4cbcbc # v3.0.5
        with:
          errors: true
          method: chat.postMessage
          token: ${{ secrets.BENNETTBOT_SLACK_BOT_TOKEN }}
          payload: |
            channel: "C069YDR4NCA"
            text: "Airlock functional tests failed: Download the trace at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id}}"
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: ":warning: Airlock functional tests failed:warning:\nDownload the trace at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id}}"
