---
name: trace-functional-tests

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 3 * * *"

permissions:
  contents: read

jobs:

  trace-functional-tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: "opensafely-core/setup-action@93841f27c28c75bf85b1a0a915e2391a06c6c8a6" # v1
        with:
          install-just: true
          install-uv: true
          cache: uv

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: ".node-version"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install node_modules
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Set up development environment
        run: just devenv

      - name: Run functional tests
        id: run_test
        run: |
          HYPOTHESIS_MAX_EXAMPLES=100 just test -k functional --tracing retain-on-failure
        
      - name: Upload trace artifact
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
            name: test-results-trace
            path: test-results/**/trace.zip

      - name: Notify slack of failures
        if: failure()
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          errors: true
          method: chat.postMessage
          token: ${{ secrets.BENNETTBOT_SLACK_BOT_TOKEN }}
          payload: |
            channel: "C069YDR4NCA"
            text: "Airlock functional tests failed: Download the trace at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id}}"
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: ":warning: Airlock functional tests failed:warning:\nDownload the trace at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id}}"
